# Generated by Django 5.0.7 on 2024-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_compagny_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.DateField(),
        ),
    ]
