# Generated by Django 5.0.7 on 2024-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_job_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.AddField(
            model_name='job',
            name='endDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='startDate',
            field=models.DateField(auto_now=True),
        ),
    ]
