# Generated by Django 5.0.7 on 2024-08-06 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_job_duration_job_enddate_job_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
