# Generated by Django 5.0.7 on 2024-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_job_enddate_alter_job_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
