# Generated by Django 5.0.7 on 2024-08-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagny', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('skills', models.JSONField(default=list)),
                ('url', models.URLField()),
            ],
        ),
    ]
