# Generated by Django 5.0.7 on 2024-08-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='compagny',
            field=models.CharField(max_length=60),
        ),
    ]
