# Generated by Django 5.0.7 on 2024-08-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_job_compagny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='compagny',
            new_name='company',
        ),
    ]
