# Generated by Django 5.0.7 on 2024-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_job_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.DurationField(),
        ),
    ]
