name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.prwozny }}
          password: ${{ secrets.dckr_pat_mxrA6ynFkndA6YGlLPR1XjVp428 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.prwozny }}/django-react-portfolio:latest

      - name: Logout from Docker Hub
        run: docker logout
